import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
    nested,
}: {
  children: React.ReactNode,
  nested: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="bg-red-500 h-64 w-full">
        {nested}
      </div>
      <div className="bg-blue-500 h-64 w-full">
        {children}
      </div>
      </body>
    </html>
  )
}
